import LogoNav from "../../shared/LogoNav";
import SecondaryNav from "../../shared/SecondaryNav";
import TertioryNav from "../../shared/TertioryNav";

const Center = () => {
    return (
        <div>

            <LogoNav></LogoNav>
            <SecondaryNav></SecondaryNav>
            <TertioryNav></TertioryNav>

            <div className="w-full h-96 bg-yellow-700 flex justify-center items-center text-center text-white">
  <h1 className="text-3xl">Centers And Institutions</h1>
</div>


            <div className="mx-3 lg:mx-auto lg:max-w-4xl xl:max-w-7xl 2xl:max-w-7xl py-10">
            <div className="flex flex-col">
                <h1 className="font-normal text-2xl text-[#f4253f] py-5">Center for International Language and Culture</h1>
                <div className="flex flex-col gap-3">
                    <p>Welcome to the Canadian University of Bangladesh&apos;s Center for International Language and Culture, where diversity meets academic excellence. Our center is a vibrant hub that fosters linguistic proficiency and celebrates the rich tapestry of global cultures.</p>
                    <p>At CUB, we offer a spectrum of language programs designed to empower students with the skills needed to navigate an interconnected world. Whether you&apos;re exploring English for academic purposes, enhancing your proficiency in Korean or delving into the intricacies of other international languages, our dedicated faculty is committed to providing an immersive and enriching learning experience.</p>
                    <p>Embrace a multicultural environment that promotes cross-cultural understanding, communication, and collaboration. Join us on a journey of language exploration and cultural exchange, where every word spoken opens a door to new connections and opportunities.</p>
                    <p>Discover the world through language at the Canadian University of Bangladesh&apos;s Center for International Language and Culture. Your pathway to global communication and cultural fluency begins here.</p>
                </div>
            </div>
            <div className="flex flex-col">
                <h1 className="font-normal text-2xl text-[#f4253f] py-5">Artificial Intelligence and Machine Learning Cell (AIMLC)</h1>
                <div className="flex flex-col gap-3">
                <div className="flex flex-col gap-1">
                    <h2 className="text-[#f4253f] text-base">Objective:</h2>
                    <p>In conjunction with the industry, AIMLC aspires to build AI solutions that aim to answer contemporary challenges in Bangladesh and internationally. We continue to create high-quality research and trained professionals with the knowledge and potential to be at the forefront of Bangladesh&apos;s AI revolution in the next few years.</p>                        
                    </div>
                    <div>
                    <h2 className="text-[#f4253f] text-base">Description:</h2>
                    <p>The Artificial Intelligence and Machine Learning Lab&apos;s researchers are constantly working on developing intelligent solutions that can understand language and emotion, mine actionable information from social media, develop nature-inspired algorithms for data classification and clustering, detect activities from massive amounts of data generated by IoT devices, and develop sustainable computation and generation of game scenarios for intelligent game automation. This is only the beginning; as artificial intelligence innovation fuels the AI revolution, machine learning will have a tremendous influence on many parts of our life, including politics, medicine, education, and transportation, affecting everyone everywhere.</p>                        
                    </div>
                </div>
            </div>
            </div>



        </div>
    );
};

export default Center;